import { ObjectId } from "mongodb";
import { getDb } from "../db/connection.js";
import { getMatchesCollection, getApplicantsCollection } from "../db/collections.js";
import type { MatchDoc, MatchStatus } from "../models/match.model.js";
import type { ApplicantDoc } from "../models/applicant.model.js";
import type { CoupleProposal } from "../matching/engine.js";
import type { PaginatedResult } from "./admin.service.js";

// ── View type (ObjectIds serialised to strings) ───────────────────────────────

export type MatchView = Omit<MatchDoc, "_id" | "applicantAId" | "applicantBId"> & {
  id: string;
  applicantAId: string;
  applicantBId: string;
};

function toView(doc: MatchDoc): MatchView {
  const { _id, applicantAId, applicantBId, ...rest } = doc;
  return {
    id: _id.toHexString(),
    applicantAId: applicantAId.toHexString(),
    applicantBId: applicantBId.toHexString(),
    ...rest,
  };
}

// ── CRUD ──────────────────────────────────────────────────────────────────────

/**
 * Returns a paginated list of matches.
 * Optionally filtered by status or by a participant's applicant ID.
 */
export async function listMatches(
  page: number,
  limit: number,
  status?: MatchStatus,
  participantId?: string,
): Promise<PaginatedResult<MatchView>> {
  const db  = await getDb();
  const col = getMatchesCollection(db);

  const filter: Record<string, unknown> = {};
  if (status) filter.status = status;
  if (participantId) {
    let oid: ObjectId;
    try { oid = new ObjectId(participantId); } catch {
      return { data: [], total: 0, page, limit, totalPages: 0 };
    }
    filter.$or = [{ applicantAId: oid }, { applicantBId: oid }];
  }

  const skip = (page - 1) * limit;

  const [docs, total] = await Promise.all([
    col.find(filter).sort({ score: -1 }).skip(skip).limit(limit).toArray(),
    col.countDocuments(filter),
  ]);

  return {
    data: docs.map(toView),
    total,
    page,
    limit,
    totalPages: Math.ceil(total / limit),
  };
}

/**
 * Partially updates a match (status and/or notes).
 * Returns the updated view, or null if not found.
 */
export async function updateMatch(
  id: string,
  updates: { status?: MatchStatus; notes?: string },
): Promise<MatchView | null> {
  const db  = await getDb();
  const col = getMatchesCollection(db);

  let oid: ObjectId;
  try { oid = new ObjectId(id); } catch { return null; }

  const result = await col.findOneAndUpdate(
    { _id: oid },
    { $set: { ...updates, updatedAt: new Date() } },
    { returnDocument: "after" },
  );

  return result ? toView(result) : null;
}

/**
 * Hard-deletes a match. Returns true if a document was removed.
 */
export async function deleteMatch(id: string): Promise<boolean> {
  const db  = await getDb();
  const col = getMatchesCollection(db);

  let oid: ObjectId;
  try { oid = new ObjectId(id); } catch { return false; }

  const result = await col.deleteOne({ _id: oid });
  return result.deletedCount > 0;
}

// ── Proposal persistence ──────────────────────────────────────────────────────

/**
 * Persists couple proposals generated by the matching engine.
 *
 * Skips a pair if an active (non-failed) match already exists for it.
 * Handles MongoDB duplicate-key errors (11000) for concurrent saves.
 *
 * Returns the count of newly inserted documents.
 */
export async function saveMatchProposals(
  proposals: CoupleProposal[],
  algorithm: string,
): Promise<number> {
  if (proposals.length === 0) return 0;

  const db  = await getDb();
  const col = getMatchesCollection(db);

  const now = new Date();
  let saved = 0;

  for (const p of proposals) {
    // Skip if an active match already exists for this canonical pair
    const existing = await col.findOne({
      applicantAId: p.applicantAId,
      applicantBId: p.applicantBId,
      status: { $ne: "failed" },
    });
    if (existing) continue;

    try {
      await col.insertOne({
        _id:             new ObjectId(),
        applicantAId:    p.applicantAId,
        applicantAAlias: p.applicantAAlias,
        applicantBId:    p.applicantBId,
        applicantBAlias: p.applicantBAlias,
        score:           p.score,
        algorithm,
        status:          "proposed",
        createdAt:       now,
        updatedAt:       now,
      });
      saved++;
    } catch (err: unknown) {
      // Race condition duplicate — skip silently
      if ((err as { code?: number })?.code !== 11000) throw err;
    }
  }

  return saved;
}

/**
 * Loads all active applicants from the DB.
 * Used by the matching controller to generate couple proposals.
 */
export async function loadActiveApplicants(): Promise<ApplicantDoc[]> {
  const db  = await getDb();
  const col = getApplicantsCollection(db);
  return col.find({ status: "active" }).toArray();
}
